### ISSUE TITLE
Double underlines under error and warnings

### ISSUE THREAD

**Issue by Lirrrx** [luciascarlet/tailwind-moon-vscode#3]
Why are there double underlines under errror and warning in editor? I think only squiggle is more clean.
<img width="455" alt="CleanShot 2022-02-19 at 22 44 59@2x" src="https://user-images.githubusercontent.com/58344309/154816665-3edd38ac-297e-44bc-a8e6-7f754099cab3.png">

**Comment by luciascarlet** [comment]
You're right – this is a mistake presumably caused by it originally being the Tailwind Breeze theme which was modified for dark mode. I'm not sure why I haven't really encountered this myself, but that's definitely not how it should be. I'm kinda slow with working on this theme though so I'm not sure when I'm going to patch it... definitely expect to see it in the next update though
